services:
  jdownloader-web:
    build:
      context: .
      args:
        VITE_JD_API_URL: /api
    image: jdownloader-web
    container_name: jdownloader-web
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - jdownloader_net

networks:
  jdownloader_net:
    external: true
    name: jdownloader_net
