services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader-2
    restart: unless-stopped
    ports:
      - "5800:5800"
    volumes:
      - ./jd2-config:/config:rw
      - ./downloads:/output:rw
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - TZ=${TZ:-Europe/Rome}
    networks:
      - npm-nw

  jdownloader-web:
    build:
      context: .
      args:
        VITE_JD_API_URL: /api
    image: jdownloader-web
    container_name: jdownloader-web
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - npm-nw

networks:
  npm-nw:
    external: true
